# Generated by Django 3.0 on 2023-04-29 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('very-high', 'very-high'), ('high', 'high'), ('medium', 'medium'), ('low', 'low'), ('very-low', 'very-low')], default='very-high', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('activity_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.Activity')),
            ],
            options={
                'db_table': 'todos',
            },
        ),
    ]
